#include "EmJetHistos.h"

using std::string;
using std::unordered_map;
using std::vector;

EmJetHistos::EmJetHistos()
{
  TH1::SetDefaultSumw2();

  /*[[[cog
    import histo_definitions as mod
    mod.generate_histo_map_init()
    ]]]*/
  hist1d["ht"] = new TH1F("ht", "ht" , 100, 0, 2500);
  hist1d["jet_pt"] = new TH1F("jet_pt", "jet_pt" , 150, 0, 1500);
  hist1d["jet_eta"] = new TH1F("jet_eta", "jet_eta" , 100, -5, 5);
  hist1d["jet_phi"] = new TH1F("jet_phi", "jet_phi" , 100, -5, 5);
  hist1d["jet_nTrack"] = new TH1F("jet_nTrack", "jet_nTrack" , 100, 0.0, 100);
  hist1d["jet_nTrackPostCut"] = new TH1F("jet_nTrackPostCut", "jet_nTrackPostCut" , 100, 0.0, 100);
  hist1d["jet_csv"] = new TH1F("jet_csv", "jet_csv" , 100, 0.0, 1.0);
  hist1d["nJet_tag"] = new TH1F("nJet_tag", "nJet_tag" , 10, 0, 10);
  hist1d["n1tag"] = new TH1F("n1tag", "n1tag" , 500, 0, 10000);
  hist1d["n2tag"] = new TH1F("n2tag", "n2tag" , 400, 0, 200);
  hist1d["n1tag__0"] = new TH1F("n1tag__0", "n1tag__0" , 500, 0, 10000);
  hist1d["n1tag__1"] = new TH1F("n1tag__1", "n1tag__1" , 500, 0, 10000);
  hist1d["n1tag__2"] = new TH1F("n1tag__2", "n1tag__2" , 500, 0, 10000);
  hist1d["n1tag__3"] = new TH1F("n1tag__3", "n1tag__3" , 500, 0, 10000);
  hist1d["n1tag__4"] = new TH1F("n1tag__4", "n1tag__4" , 500, 0, 10000);
  hist1d["n1tag__5"] = new TH1F("n1tag__5", "n1tag__5" , 500, 0, 10000);
  hist1d["n1tag__6"] = new TH1F("n1tag__6", "n1tag__6" , 500, 0, 10000);
  hist1d["n1tag__7"] = new TH1F("n1tag__7", "n1tag__7" , 500, 0, 10000);
  hist1d["n1tag__8"] = new TH1F("n1tag__8", "n1tag__8" , 500, 0, 10000);
  hist1d["n1tag__9"] = new TH1F("n1tag__9", "n1tag__9" , 500, 0, 10000);
  hist1d["n2tag__0"] = new TH1F("n2tag__0", "n2tag__0" , 400, 0, 200);
  hist1d["n2tag__1"] = new TH1F("n2tag__1", "n2tag__1" , 400, 0, 200);
  hist1d["n2tag__2"] = new TH1F("n2tag__2", "n2tag__2" , 400, 0, 200);
  hist1d["n2tag__3"] = new TH1F("n2tag__3", "n2tag__3" , 400, 0, 200);
  hist1d["n2tag__4"] = new TH1F("n2tag__4", "n2tag__4" , 400, 0, 200);
  hist1d["n2tag__5"] = new TH1F("n2tag__5", "n2tag__5" , 400, 0, 200);
  hist1d["n2tag__6"] = new TH1F("n2tag__6", "n2tag__6" , 400, 0, 200);
  hist1d["n2tag__7"] = new TH1F("n2tag__7", "n2tag__7" , 400, 0, 200);
  hist1d["n2tag__8"] = new TH1F("n2tag__8", "n2tag__8" , 400, 0, 200);
  hist1d["n2tag__9"] = new TH1F("n2tag__9", "n2tag__9" , 400, 0, 200);
  hist1d["jet_pt__B"] = new TH1F("jet_pt__B", "jet_pt__B" , 150, 0, 1500);
  hist1d["jet_pt__L"] = new TH1F("jet_pt__L", "jet_pt__L" , 150, 0, 1500);
  hist1d["jet_eta__B"] = new TH1F("jet_eta__B", "jet_eta__B" , 100, -5, 5);
  hist1d["jet_eta__L"] = new TH1F("jet_eta__L", "jet_eta__L" , 100, -5, 5);
  hist1d["jet_phi__B"] = new TH1F("jet_phi__B", "jet_phi__B" , 100, -5, 5);
  hist1d["jet_phi__L"] = new TH1F("jet_phi__L", "jet_phi__L" , 100, -5, 5);
  hist1d["jet_nTrack__B"] = new TH1F("jet_nTrack__B", "jet_nTrack__B" , 100, 0.0, 100);
  hist1d["jet_nTrack__L"] = new TH1F("jet_nTrack__L", "jet_nTrack__L" , 100, 0.0, 100);
  hist1d["jet_nTrackPostCut__B"] = new TH1F("jet_nTrackPostCut__B", "jet_nTrackPostCut__B" , 100, 0.0, 100);
  hist1d["jet_nTrackPostCut__L"] = new TH1F("jet_nTrackPostCut__L", "jet_nTrackPostCut__L" , 100, 0.0, 100);
  hist1d["jet_csv__B"] = new TH1F("jet_csv__B", "jet_csv__B" , 100, 0.0, 1.0);
  hist1d["jet_csv__L"] = new TH1F("jet_csv__L", "jet_csv__L" , 100, 0.0, 1.0);
  hist1d["jet_pt__Emerging"] = new TH1F("jet_pt__Emerging", "jet_pt__Emerging" , 150, 0, 1500);
  hist1d["jet_pt__Standard"] = new TH1F("jet_pt__Standard", "jet_pt__Standard" , 150, 0, 1500);
  hist1d["jet_eta__Emerging"] = new TH1F("jet_eta__Emerging", "jet_eta__Emerging" , 100, -5, 5);
  hist1d["jet_eta__Standard"] = new TH1F("jet_eta__Standard", "jet_eta__Standard" , 100, -5, 5);
  hist1d["jet_phi__Emerging"] = new TH1F("jet_phi__Emerging", "jet_phi__Emerging" , 100, -5, 5);
  hist1d["jet_phi__Standard"] = new TH1F("jet_phi__Standard", "jet_phi__Standard" , 100, -5, 5);
  hist1d["jet_nTrack__Emerging"] = new TH1F("jet_nTrack__Emerging", "jet_nTrack__Emerging" , 100, 0.0, 100);
  hist1d["jet_nTrack__Standard"] = new TH1F("jet_nTrack__Standard", "jet_nTrack__Standard" , 100, 0.0, 100);
  hist1d["jet_nTrackPostCut__Emerging"] = new TH1F("jet_nTrackPostCut__Emerging", "jet_nTrackPostCut__Emerging" , 100, 0.0, 100);
  hist1d["jet_nTrackPostCut__Standard"] = new TH1F("jet_nTrackPostCut__Standard", "jet_nTrackPostCut__Standard" , 100, 0.0, 100);
  hist1d["jet_csv__Emerging"] = new TH1F("jet_csv__Emerging", "jet_csv__Emerging" , 100, 0.0, 1.0);
  hist1d["jet_csv__Standard"] = new TH1F("jet_csv__Standard", "jet_csv__Standard" , 100, 0.0, 1.0);
  hist1d["jet_pt__B__Emerging"] = new TH1F("jet_pt__B__Emerging", "jet_pt__B__Emerging" , 150, 0, 1500);
  hist1d["jet_pt__B__Standard"] = new TH1F("jet_pt__B__Standard", "jet_pt__B__Standard" , 150, 0, 1500);
  hist1d["jet_pt__L__Emerging"] = new TH1F("jet_pt__L__Emerging", "jet_pt__L__Emerging" , 150, 0, 1500);
  hist1d["jet_pt__L__Standard"] = new TH1F("jet_pt__L__Standard", "jet_pt__L__Standard" , 150, 0, 1500);
  hist1d["jet_eta__B__Emerging"] = new TH1F("jet_eta__B__Emerging", "jet_eta__B__Emerging" , 100, -5, 5);
  hist1d["jet_eta__B__Standard"] = new TH1F("jet_eta__B__Standard", "jet_eta__B__Standard" , 100, -5, 5);
  hist1d["jet_eta__L__Emerging"] = new TH1F("jet_eta__L__Emerging", "jet_eta__L__Emerging" , 100, -5, 5);
  hist1d["jet_eta__L__Standard"] = new TH1F("jet_eta__L__Standard", "jet_eta__L__Standard" , 100, -5, 5);
  hist1d["jet_phi__B__Emerging"] = new TH1F("jet_phi__B__Emerging", "jet_phi__B__Emerging" , 100, -5, 5);
  hist1d["jet_phi__B__Standard"] = new TH1F("jet_phi__B__Standard", "jet_phi__B__Standard" , 100, -5, 5);
  hist1d["jet_phi__L__Emerging"] = new TH1F("jet_phi__L__Emerging", "jet_phi__L__Emerging" , 100, -5, 5);
  hist1d["jet_phi__L__Standard"] = new TH1F("jet_phi__L__Standard", "jet_phi__L__Standard" , 100, -5, 5);
  hist1d["jet_nTrack__B__Emerging"] = new TH1F("jet_nTrack__B__Emerging", "jet_nTrack__B__Emerging" , 100, 0.0, 100);
  hist1d["jet_nTrack__B__Standard"] = new TH1F("jet_nTrack__B__Standard", "jet_nTrack__B__Standard" , 100, 0.0, 100);
  hist1d["jet_nTrack__L__Emerging"] = new TH1F("jet_nTrack__L__Emerging", "jet_nTrack__L__Emerging" , 100, 0.0, 100);
  hist1d["jet_nTrack__L__Standard"] = new TH1F("jet_nTrack__L__Standard", "jet_nTrack__L__Standard" , 100, 0.0, 100);
  hist1d["jet_nTrackPostCut__B__Emerging"] = new TH1F("jet_nTrackPostCut__B__Emerging", "jet_nTrackPostCut__B__Emerging" , 100, 0.0, 100);
  hist1d["jet_nTrackPostCut__B__Standard"] = new TH1F("jet_nTrackPostCut__B__Standard", "jet_nTrackPostCut__B__Standard" , 100, 0.0, 100);
  hist1d["jet_nTrackPostCut__L__Emerging"] = new TH1F("jet_nTrackPostCut__L__Emerging", "jet_nTrackPostCut__L__Emerging" , 100, 0.0, 100);
  hist1d["jet_nTrackPostCut__L__Standard"] = new TH1F("jet_nTrackPostCut__L__Standard", "jet_nTrackPostCut__L__Standard" , 100, 0.0, 100);
  hist1d["jet_csv__B__Emerging"] = new TH1F("jet_csv__B__Emerging", "jet_csv__B__Emerging" , 100, 0.0, 1.0);
  hist1d["jet_csv__B__Standard"] = new TH1F("jet_csv__B__Standard", "jet_csv__B__Standard" , 100, 0.0, 1.0);
  hist1d["jet_csv__L__Emerging"] = new TH1F("jet_csv__L__Emerging", "jet_csv__L__Emerging" , 100, 0.0, 1.0);
  hist1d["jet_csv__L__Standard"] = new TH1F("jet_csv__L__Standard", "jet_csv__L__Standard" , 100, 0.0, 1.0);
  hist1d["ht__0tag"] = new TH1F("ht__0tag", "ht__0tag" , 100, 0, 2500);
  hist1d["ht__1tag"] = new TH1F("ht__1tag", "ht__1tag" , 100, 0, 2500);
  hist1d["ht__2tag"] = new TH1F("ht__2tag", "ht__2tag" , 100, 0, 2500);
  hist1d["ht__GJetPredicted0To1Tag"] = new TH1F("ht__GJetPredicted0To1Tag", "ht__GJetPredicted0To1Tag" , 100, 0, 2500);
  hist1d["ht__GJetPredicted1To2Tag"] = new TH1F("ht__GJetPredicted1To2Tag", "ht__GJetPredicted1To2Tag" , 100, 0, 2500);
  hist1d["jet_pt__0tag"] = new TH1F("jet_pt__0tag", "jet_pt__0tag" , 150, 0, 1500);
  hist1d["jet_pt__1tag"] = new TH1F("jet_pt__1tag", "jet_pt__1tag" , 150, 0, 1500);
  hist1d["jet_pt__2tag"] = new TH1F("jet_pt__2tag", "jet_pt__2tag" , 150, 0, 1500);
  hist1d["jet_pt__GJetPredicted0To1Tag"] = new TH1F("jet_pt__GJetPredicted0To1Tag", "jet_pt__GJetPredicted0To1Tag" , 150, 0, 1500);
  hist1d["jet_pt__GJetPredicted1To2Tag"] = new TH1F("jet_pt__GJetPredicted1To2Tag", "jet_pt__GJetPredicted1To2Tag" , 150, 0, 1500);
  hist1d["jet_eta__0tag"] = new TH1F("jet_eta__0tag", "jet_eta__0tag" , 100, -5, 5);
  hist1d["jet_eta__1tag"] = new TH1F("jet_eta__1tag", "jet_eta__1tag" , 100, -5, 5);
  hist1d["jet_eta__2tag"] = new TH1F("jet_eta__2tag", "jet_eta__2tag" , 100, -5, 5);
  hist1d["jet_eta__GJetPredicted0To1Tag"] = new TH1F("jet_eta__GJetPredicted0To1Tag", "jet_eta__GJetPredicted0To1Tag" , 100, -5, 5);
  hist1d["jet_eta__GJetPredicted1To2Tag"] = new TH1F("jet_eta__GJetPredicted1To2Tag", "jet_eta__GJetPredicted1To2Tag" , 100, -5, 5);
  hist1d["jet_phi__0tag"] = new TH1F("jet_phi__0tag", "jet_phi__0tag" , 100, -5, 5);
  hist1d["jet_phi__1tag"] = new TH1F("jet_phi__1tag", "jet_phi__1tag" , 100, -5, 5);
  hist1d["jet_phi__2tag"] = new TH1F("jet_phi__2tag", "jet_phi__2tag" , 100, -5, 5);
  hist1d["jet_phi__GJetPredicted0To1Tag"] = new TH1F("jet_phi__GJetPredicted0To1Tag", "jet_phi__GJetPredicted0To1Tag" , 100, -5, 5);
  hist1d["jet_phi__GJetPredicted1To2Tag"] = new TH1F("jet_phi__GJetPredicted1To2Tag", "jet_phi__GJetPredicted1To2Tag" , 100, -5, 5);
  hist1d["jet_nTrack__0tag"] = new TH1F("jet_nTrack__0tag", "jet_nTrack__0tag" , 100, 0.0, 100);
  hist1d["jet_nTrack__1tag"] = new TH1F("jet_nTrack__1tag", "jet_nTrack__1tag" , 100, 0.0, 100);
  hist1d["jet_nTrack__2tag"] = new TH1F("jet_nTrack__2tag", "jet_nTrack__2tag" , 100, 0.0, 100);
  hist1d["jet_nTrack__GJetPredicted0To1Tag"] = new TH1F("jet_nTrack__GJetPredicted0To1Tag", "jet_nTrack__GJetPredicted0To1Tag" , 100, 0.0, 100);
  hist1d["jet_nTrack__GJetPredicted1To2Tag"] = new TH1F("jet_nTrack__GJetPredicted1To2Tag", "jet_nTrack__GJetPredicted1To2Tag" , 100, 0.0, 100);
  hist1d["jet_nTrackPostCut__0tag"] = new TH1F("jet_nTrackPostCut__0tag", "jet_nTrackPostCut__0tag" , 100, 0.0, 100);
  hist1d["jet_nTrackPostCut__1tag"] = new TH1F("jet_nTrackPostCut__1tag", "jet_nTrackPostCut__1tag" , 100, 0.0, 100);
  hist1d["jet_nTrackPostCut__2tag"] = new TH1F("jet_nTrackPostCut__2tag", "jet_nTrackPostCut__2tag" , 100, 0.0, 100);
  hist1d["jet_nTrackPostCut__GJetPredicted0To1Tag"] = new TH1F("jet_nTrackPostCut__GJetPredicted0To1Tag", "jet_nTrackPostCut__GJetPredicted0To1Tag" , 100, 0.0, 100);
  hist1d["jet_nTrackPostCut__GJetPredicted1To2Tag"] = new TH1F("jet_nTrackPostCut__GJetPredicted1To2Tag", "jet_nTrackPostCut__GJetPredicted1To2Tag" , 100, 0.0, 100);
  hist1d["jet_csv__0tag"] = new TH1F("jet_csv__0tag", "jet_csv__0tag" , 100, 0.0, 1.0);
  hist1d["jet_csv__1tag"] = new TH1F("jet_csv__1tag", "jet_csv__1tag" , 100, 0.0, 1.0);
  hist1d["jet_csv__2tag"] = new TH1F("jet_csv__2tag", "jet_csv__2tag" , 100, 0.0, 1.0);
  hist1d["jet_csv__GJetPredicted0To1Tag"] = new TH1F("jet_csv__GJetPredicted0To1Tag", "jet_csv__GJetPredicted0To1Tag" , 100, 0.0, 1.0);
  hist1d["jet_csv__GJetPredicted1To2Tag"] = new TH1F("jet_csv__GJetPredicted1To2Tag", "jet_csv__GJetPredicted1To2Tag" , 100, 0.0, 1.0);
  hist1d["jet_pt__B__0tag"] = new TH1F("jet_pt__B__0tag", "jet_pt__B__0tag" , 150, 0, 1500);
  hist1d["jet_pt__B__1tag"] = new TH1F("jet_pt__B__1tag", "jet_pt__B__1tag" , 150, 0, 1500);
  hist1d["jet_pt__B__2tag"] = new TH1F("jet_pt__B__2tag", "jet_pt__B__2tag" , 150, 0, 1500);
  hist1d["jet_pt__B__GJetPredicted0To1Tag"] = new TH1F("jet_pt__B__GJetPredicted0To1Tag", "jet_pt__B__GJetPredicted0To1Tag" , 150, 0, 1500);
  hist1d["jet_pt__B__GJetPredicted1To2Tag"] = new TH1F("jet_pt__B__GJetPredicted1To2Tag", "jet_pt__B__GJetPredicted1To2Tag" , 150, 0, 1500);
  hist1d["jet_pt__L__0tag"] = new TH1F("jet_pt__L__0tag", "jet_pt__L__0tag" , 150, 0, 1500);
  hist1d["jet_pt__L__1tag"] = new TH1F("jet_pt__L__1tag", "jet_pt__L__1tag" , 150, 0, 1500);
  hist1d["jet_pt__L__2tag"] = new TH1F("jet_pt__L__2tag", "jet_pt__L__2tag" , 150, 0, 1500);
  hist1d["jet_pt__L__GJetPredicted0To1Tag"] = new TH1F("jet_pt__L__GJetPredicted0To1Tag", "jet_pt__L__GJetPredicted0To1Tag" , 150, 0, 1500);
  hist1d["jet_pt__L__GJetPredicted1To2Tag"] = new TH1F("jet_pt__L__GJetPredicted1To2Tag", "jet_pt__L__GJetPredicted1To2Tag" , 150, 0, 1500);
  hist1d["jet_eta__B__0tag"] = new TH1F("jet_eta__B__0tag", "jet_eta__B__0tag" , 100, -5, 5);
  hist1d["jet_eta__B__1tag"] = new TH1F("jet_eta__B__1tag", "jet_eta__B__1tag" , 100, -5, 5);
  hist1d["jet_eta__B__2tag"] = new TH1F("jet_eta__B__2tag", "jet_eta__B__2tag" , 100, -5, 5);
  hist1d["jet_eta__B__GJetPredicted0To1Tag"] = new TH1F("jet_eta__B__GJetPredicted0To1Tag", "jet_eta__B__GJetPredicted0To1Tag" , 100, -5, 5);
  hist1d["jet_eta__B__GJetPredicted1To2Tag"] = new TH1F("jet_eta__B__GJetPredicted1To2Tag", "jet_eta__B__GJetPredicted1To2Tag" , 100, -5, 5);
  hist1d["jet_eta__L__0tag"] = new TH1F("jet_eta__L__0tag", "jet_eta__L__0tag" , 100, -5, 5);
  hist1d["jet_eta__L__1tag"] = new TH1F("jet_eta__L__1tag", "jet_eta__L__1tag" , 100, -5, 5);
  hist1d["jet_eta__L__2tag"] = new TH1F("jet_eta__L__2tag", "jet_eta__L__2tag" , 100, -5, 5);
  hist1d["jet_eta__L__GJetPredicted0To1Tag"] = new TH1F("jet_eta__L__GJetPredicted0To1Tag", "jet_eta__L__GJetPredicted0To1Tag" , 100, -5, 5);
  hist1d["jet_eta__L__GJetPredicted1To2Tag"] = new TH1F("jet_eta__L__GJetPredicted1To2Tag", "jet_eta__L__GJetPredicted1To2Tag" , 100, -5, 5);
  hist1d["jet_phi__B__0tag"] = new TH1F("jet_phi__B__0tag", "jet_phi__B__0tag" , 100, -5, 5);
  hist1d["jet_phi__B__1tag"] = new TH1F("jet_phi__B__1tag", "jet_phi__B__1tag" , 100, -5, 5);
  hist1d["jet_phi__B__2tag"] = new TH1F("jet_phi__B__2tag", "jet_phi__B__2tag" , 100, -5, 5);
  hist1d["jet_phi__B__GJetPredicted0To1Tag"] = new TH1F("jet_phi__B__GJetPredicted0To1Tag", "jet_phi__B__GJetPredicted0To1Tag" , 100, -5, 5);
  hist1d["jet_phi__B__GJetPredicted1To2Tag"] = new TH1F("jet_phi__B__GJetPredicted1To2Tag", "jet_phi__B__GJetPredicted1To2Tag" , 100, -5, 5);
  hist1d["jet_phi__L__0tag"] = new TH1F("jet_phi__L__0tag", "jet_phi__L__0tag" , 100, -5, 5);
  hist1d["jet_phi__L__1tag"] = new TH1F("jet_phi__L__1tag", "jet_phi__L__1tag" , 100, -5, 5);
  hist1d["jet_phi__L__2tag"] = new TH1F("jet_phi__L__2tag", "jet_phi__L__2tag" , 100, -5, 5);
  hist1d["jet_phi__L__GJetPredicted0To1Tag"] = new TH1F("jet_phi__L__GJetPredicted0To1Tag", "jet_phi__L__GJetPredicted0To1Tag" , 100, -5, 5);
  hist1d["jet_phi__L__GJetPredicted1To2Tag"] = new TH1F("jet_phi__L__GJetPredicted1To2Tag", "jet_phi__L__GJetPredicted1To2Tag" , 100, -5, 5);
  hist1d["jet_nTrack__B__0tag"] = new TH1F("jet_nTrack__B__0tag", "jet_nTrack__B__0tag" , 100, 0.0, 100);
  hist1d["jet_nTrack__B__1tag"] = new TH1F("jet_nTrack__B__1tag", "jet_nTrack__B__1tag" , 100, 0.0, 100);
  hist1d["jet_nTrack__B__2tag"] = new TH1F("jet_nTrack__B__2tag", "jet_nTrack__B__2tag" , 100, 0.0, 100);
  hist1d["jet_nTrack__B__GJetPredicted0To1Tag"] = new TH1F("jet_nTrack__B__GJetPredicted0To1Tag", "jet_nTrack__B__GJetPredicted0To1Tag" , 100, 0.0, 100);
  hist1d["jet_nTrack__B__GJetPredicted1To2Tag"] = new TH1F("jet_nTrack__B__GJetPredicted1To2Tag", "jet_nTrack__B__GJetPredicted1To2Tag" , 100, 0.0, 100);
  hist1d["jet_nTrack__L__0tag"] = new TH1F("jet_nTrack__L__0tag", "jet_nTrack__L__0tag" , 100, 0.0, 100);
  hist1d["jet_nTrack__L__1tag"] = new TH1F("jet_nTrack__L__1tag", "jet_nTrack__L__1tag" , 100, 0.0, 100);
  hist1d["jet_nTrack__L__2tag"] = new TH1F("jet_nTrack__L__2tag", "jet_nTrack__L__2tag" , 100, 0.0, 100);
  hist1d["jet_nTrack__L__GJetPredicted0To1Tag"] = new TH1F("jet_nTrack__L__GJetPredicted0To1Tag", "jet_nTrack__L__GJetPredicted0To1Tag" , 100, 0.0, 100);
  hist1d["jet_nTrack__L__GJetPredicted1To2Tag"] = new TH1F("jet_nTrack__L__GJetPredicted1To2Tag", "jet_nTrack__L__GJetPredicted1To2Tag" , 100, 0.0, 100);
  hist1d["jet_nTrackPostCut__B__0tag"] = new TH1F("jet_nTrackPostCut__B__0tag", "jet_nTrackPostCut__B__0tag" , 100, 0.0, 100);
  hist1d["jet_nTrackPostCut__B__1tag"] = new TH1F("jet_nTrackPostCut__B__1tag", "jet_nTrackPostCut__B__1tag" , 100, 0.0, 100);
  hist1d["jet_nTrackPostCut__B__2tag"] = new TH1F("jet_nTrackPostCut__B__2tag", "jet_nTrackPostCut__B__2tag" , 100, 0.0, 100);
  hist1d["jet_nTrackPostCut__B__GJetPredicted0To1Tag"] = new TH1F("jet_nTrackPostCut__B__GJetPredicted0To1Tag", "jet_nTrackPostCut__B__GJetPredicted0To1Tag" , 100, 0.0, 100);
  hist1d["jet_nTrackPostCut__B__GJetPredicted1To2Tag"] = new TH1F("jet_nTrackPostCut__B__GJetPredicted1To2Tag", "jet_nTrackPostCut__B__GJetPredicted1To2Tag" , 100, 0.0, 100);
  hist1d["jet_nTrackPostCut__L__0tag"] = new TH1F("jet_nTrackPostCut__L__0tag", "jet_nTrackPostCut__L__0tag" , 100, 0.0, 100);
  hist1d["jet_nTrackPostCut__L__1tag"] = new TH1F("jet_nTrackPostCut__L__1tag", "jet_nTrackPostCut__L__1tag" , 100, 0.0, 100);
  hist1d["jet_nTrackPostCut__L__2tag"] = new TH1F("jet_nTrackPostCut__L__2tag", "jet_nTrackPostCut__L__2tag" , 100, 0.0, 100);
  hist1d["jet_nTrackPostCut__L__GJetPredicted0To1Tag"] = new TH1F("jet_nTrackPostCut__L__GJetPredicted0To1Tag", "jet_nTrackPostCut__L__GJetPredicted0To1Tag" , 100, 0.0, 100);
  hist1d["jet_nTrackPostCut__L__GJetPredicted1To2Tag"] = new TH1F("jet_nTrackPostCut__L__GJetPredicted1To2Tag", "jet_nTrackPostCut__L__GJetPredicted1To2Tag" , 100, 0.0, 100);
  hist1d["jet_csv__B__0tag"] = new TH1F("jet_csv__B__0tag", "jet_csv__B__0tag" , 100, 0.0, 1.0);
  hist1d["jet_csv__B__1tag"] = new TH1F("jet_csv__B__1tag", "jet_csv__B__1tag" , 100, 0.0, 1.0);
  hist1d["jet_csv__B__2tag"] = new TH1F("jet_csv__B__2tag", "jet_csv__B__2tag" , 100, 0.0, 1.0);
  hist1d["jet_csv__B__GJetPredicted0To1Tag"] = new TH1F("jet_csv__B__GJetPredicted0To1Tag", "jet_csv__B__GJetPredicted0To1Tag" , 100, 0.0, 1.0);
  hist1d["jet_csv__B__GJetPredicted1To2Tag"] = new TH1F("jet_csv__B__GJetPredicted1To2Tag", "jet_csv__B__GJetPredicted1To2Tag" , 100, 0.0, 1.0);
  hist1d["jet_csv__L__0tag"] = new TH1F("jet_csv__L__0tag", "jet_csv__L__0tag" , 100, 0.0, 1.0);
  hist1d["jet_csv__L__1tag"] = new TH1F("jet_csv__L__1tag", "jet_csv__L__1tag" , 100, 0.0, 1.0);
  hist1d["jet_csv__L__2tag"] = new TH1F("jet_csv__L__2tag", "jet_csv__L__2tag" , 100, 0.0, 1.0);
  hist1d["jet_csv__L__GJetPredicted0To1Tag"] = new TH1F("jet_csv__L__GJetPredicted0To1Tag", "jet_csv__L__GJetPredicted0To1Tag" , 100, 0.0, 1.0);
  hist1d["jet_csv__L__GJetPredicted1To2Tag"] = new TH1F("jet_csv__L__GJetPredicted1To2Tag", "jet_csv__L__GJetPredicted1To2Tag" , 100, 0.0, 1.0);
  hist1d["jet_pt__Emerging__0tag"] = new TH1F("jet_pt__Emerging__0tag", "jet_pt__Emerging__0tag" , 150, 0, 1500);
  hist1d["jet_pt__Emerging__1tag"] = new TH1F("jet_pt__Emerging__1tag", "jet_pt__Emerging__1tag" , 150, 0, 1500);
  hist1d["jet_pt__Emerging__2tag"] = new TH1F("jet_pt__Emerging__2tag", "jet_pt__Emerging__2tag" , 150, 0, 1500);
  hist1d["jet_pt__Emerging__GJetPredicted0To1Tag"] = new TH1F("jet_pt__Emerging__GJetPredicted0To1Tag", "jet_pt__Emerging__GJetPredicted0To1Tag" , 150, 0, 1500);
  hist1d["jet_pt__Emerging__GJetPredicted1To2Tag"] = new TH1F("jet_pt__Emerging__GJetPredicted1To2Tag", "jet_pt__Emerging__GJetPredicted1To2Tag" , 150, 0, 1500);
  hist1d["jet_pt__Standard__0tag"] = new TH1F("jet_pt__Standard__0tag", "jet_pt__Standard__0tag" , 150, 0, 1500);
  hist1d["jet_pt__Standard__1tag"] = new TH1F("jet_pt__Standard__1tag", "jet_pt__Standard__1tag" , 150, 0, 1500);
  hist1d["jet_pt__Standard__2tag"] = new TH1F("jet_pt__Standard__2tag", "jet_pt__Standard__2tag" , 150, 0, 1500);
  hist1d["jet_pt__Standard__GJetPredicted0To1Tag"] = new TH1F("jet_pt__Standard__GJetPredicted0To1Tag", "jet_pt__Standard__GJetPredicted0To1Tag" , 150, 0, 1500);
  hist1d["jet_pt__Standard__GJetPredicted1To2Tag"] = new TH1F("jet_pt__Standard__GJetPredicted1To2Tag", "jet_pt__Standard__GJetPredicted1To2Tag" , 150, 0, 1500);
  hist1d["jet_eta__Emerging__0tag"] = new TH1F("jet_eta__Emerging__0tag", "jet_eta__Emerging__0tag" , 100, -5, 5);
  hist1d["jet_eta__Emerging__1tag"] = new TH1F("jet_eta__Emerging__1tag", "jet_eta__Emerging__1tag" , 100, -5, 5);
  hist1d["jet_eta__Emerging__2tag"] = new TH1F("jet_eta__Emerging__2tag", "jet_eta__Emerging__2tag" , 100, -5, 5);
  hist1d["jet_eta__Emerging__GJetPredicted0To1Tag"] = new TH1F("jet_eta__Emerging__GJetPredicted0To1Tag", "jet_eta__Emerging__GJetPredicted0To1Tag" , 100, -5, 5);
  hist1d["jet_eta__Emerging__GJetPredicted1To2Tag"] = new TH1F("jet_eta__Emerging__GJetPredicted1To2Tag", "jet_eta__Emerging__GJetPredicted1To2Tag" , 100, -5, 5);
  hist1d["jet_eta__Standard__0tag"] = new TH1F("jet_eta__Standard__0tag", "jet_eta__Standard__0tag" , 100, -5, 5);
  hist1d["jet_eta__Standard__1tag"] = new TH1F("jet_eta__Standard__1tag", "jet_eta__Standard__1tag" , 100, -5, 5);
  hist1d["jet_eta__Standard__2tag"] = new TH1F("jet_eta__Standard__2tag", "jet_eta__Standard__2tag" , 100, -5, 5);
  hist1d["jet_eta__Standard__GJetPredicted0To1Tag"] = new TH1F("jet_eta__Standard__GJetPredicted0To1Tag", "jet_eta__Standard__GJetPredicted0To1Tag" , 100, -5, 5);
  hist1d["jet_eta__Standard__GJetPredicted1To2Tag"] = new TH1F("jet_eta__Standard__GJetPredicted1To2Tag", "jet_eta__Standard__GJetPredicted1To2Tag" , 100, -5, 5);
  hist1d["jet_phi__Emerging__0tag"] = new TH1F("jet_phi__Emerging__0tag", "jet_phi__Emerging__0tag" , 100, -5, 5);
  hist1d["jet_phi__Emerging__1tag"] = new TH1F("jet_phi__Emerging__1tag", "jet_phi__Emerging__1tag" , 100, -5, 5);
  hist1d["jet_phi__Emerging__2tag"] = new TH1F("jet_phi__Emerging__2tag", "jet_phi__Emerging__2tag" , 100, -5, 5);
  hist1d["jet_phi__Emerging__GJetPredicted0To1Tag"] = new TH1F("jet_phi__Emerging__GJetPredicted0To1Tag", "jet_phi__Emerging__GJetPredicted0To1Tag" , 100, -5, 5);
  hist1d["jet_phi__Emerging__GJetPredicted1To2Tag"] = new TH1F("jet_phi__Emerging__GJetPredicted1To2Tag", "jet_phi__Emerging__GJetPredicted1To2Tag" , 100, -5, 5);
  hist1d["jet_phi__Standard__0tag"] = new TH1F("jet_phi__Standard__0tag", "jet_phi__Standard__0tag" , 100, -5, 5);
  hist1d["jet_phi__Standard__1tag"] = new TH1F("jet_phi__Standard__1tag", "jet_phi__Standard__1tag" , 100, -5, 5);
  hist1d["jet_phi__Standard__2tag"] = new TH1F("jet_phi__Standard__2tag", "jet_phi__Standard__2tag" , 100, -5, 5);
  hist1d["jet_phi__Standard__GJetPredicted0To1Tag"] = new TH1F("jet_phi__Standard__GJetPredicted0To1Tag", "jet_phi__Standard__GJetPredicted0To1Tag" , 100, -5, 5);
  hist1d["jet_phi__Standard__GJetPredicted1To2Tag"] = new TH1F("jet_phi__Standard__GJetPredicted1To2Tag", "jet_phi__Standard__GJetPredicted1To2Tag" , 100, -5, 5);
  hist1d["jet_nTrack__Emerging__0tag"] = new TH1F("jet_nTrack__Emerging__0tag", "jet_nTrack__Emerging__0tag" , 100, 0.0, 100);
  hist1d["jet_nTrack__Emerging__1tag"] = new TH1F("jet_nTrack__Emerging__1tag", "jet_nTrack__Emerging__1tag" , 100, 0.0, 100);
  hist1d["jet_nTrack__Emerging__2tag"] = new TH1F("jet_nTrack__Emerging__2tag", "jet_nTrack__Emerging__2tag" , 100, 0.0, 100);
  hist1d["jet_nTrack__Emerging__GJetPredicted0To1Tag"] = new TH1F("jet_nTrack__Emerging__GJetPredicted0To1Tag", "jet_nTrack__Emerging__GJetPredicted0To1Tag" , 100, 0.0, 100);
  hist1d["jet_nTrack__Emerging__GJetPredicted1To2Tag"] = new TH1F("jet_nTrack__Emerging__GJetPredicted1To2Tag", "jet_nTrack__Emerging__GJetPredicted1To2Tag" , 100, 0.0, 100);
  hist1d["jet_nTrack__Standard__0tag"] = new TH1F("jet_nTrack__Standard__0tag", "jet_nTrack__Standard__0tag" , 100, 0.0, 100);
  hist1d["jet_nTrack__Standard__1tag"] = new TH1F("jet_nTrack__Standard__1tag", "jet_nTrack__Standard__1tag" , 100, 0.0, 100);
  hist1d["jet_nTrack__Standard__2tag"] = new TH1F("jet_nTrack__Standard__2tag", "jet_nTrack__Standard__2tag" , 100, 0.0, 100);
  hist1d["jet_nTrack__Standard__GJetPredicted0To1Tag"] = new TH1F("jet_nTrack__Standard__GJetPredicted0To1Tag", "jet_nTrack__Standard__GJetPredicted0To1Tag" , 100, 0.0, 100);
  hist1d["jet_nTrack__Standard__GJetPredicted1To2Tag"] = new TH1F("jet_nTrack__Standard__GJetPredicted1To2Tag", "jet_nTrack__Standard__GJetPredicted1To2Tag" , 100, 0.0, 100);
  hist1d["jet_nTrackPostCut__Emerging__0tag"] = new TH1F("jet_nTrackPostCut__Emerging__0tag", "jet_nTrackPostCut__Emerging__0tag" , 100, 0.0, 100);
  hist1d["jet_nTrackPostCut__Emerging__1tag"] = new TH1F("jet_nTrackPostCut__Emerging__1tag", "jet_nTrackPostCut__Emerging__1tag" , 100, 0.0, 100);
  hist1d["jet_nTrackPostCut__Emerging__2tag"] = new TH1F("jet_nTrackPostCut__Emerging__2tag", "jet_nTrackPostCut__Emerging__2tag" , 100, 0.0, 100);
  hist1d["jet_nTrackPostCut__Emerging__GJetPredicted0To1Tag"] = new TH1F("jet_nTrackPostCut__Emerging__GJetPredicted0To1Tag", "jet_nTrackPostCut__Emerging__GJetPredicted0To1Tag" , 100, 0.0, 100);
  hist1d["jet_nTrackPostCut__Emerging__GJetPredicted1To2Tag"] = new TH1F("jet_nTrackPostCut__Emerging__GJetPredicted1To2Tag", "jet_nTrackPostCut__Emerging__GJetPredicted1To2Tag" , 100, 0.0, 100);
  hist1d["jet_nTrackPostCut__Standard__0tag"] = new TH1F("jet_nTrackPostCut__Standard__0tag", "jet_nTrackPostCut__Standard__0tag" , 100, 0.0, 100);
  hist1d["jet_nTrackPostCut__Standard__1tag"] = new TH1F("jet_nTrackPostCut__Standard__1tag", "jet_nTrackPostCut__Standard__1tag" , 100, 0.0, 100);
  hist1d["jet_nTrackPostCut__Standard__2tag"] = new TH1F("jet_nTrackPostCut__Standard__2tag", "jet_nTrackPostCut__Standard__2tag" , 100, 0.0, 100);
  hist1d["jet_nTrackPostCut__Standard__GJetPredicted0To1Tag"] = new TH1F("jet_nTrackPostCut__Standard__GJetPredicted0To1Tag", "jet_nTrackPostCut__Standard__GJetPredicted0To1Tag" , 100, 0.0, 100);
  hist1d["jet_nTrackPostCut__Standard__GJetPredicted1To2Tag"] = new TH1F("jet_nTrackPostCut__Standard__GJetPredicted1To2Tag", "jet_nTrackPostCut__Standard__GJetPredicted1To2Tag" , 100, 0.0, 100);
  hist1d["jet_csv__Emerging__0tag"] = new TH1F("jet_csv__Emerging__0tag", "jet_csv__Emerging__0tag" , 100, 0.0, 1.0);
  hist1d["jet_csv__Emerging__1tag"] = new TH1F("jet_csv__Emerging__1tag", "jet_csv__Emerging__1tag" , 100, 0.0, 1.0);
  hist1d["jet_csv__Emerging__2tag"] = new TH1F("jet_csv__Emerging__2tag", "jet_csv__Emerging__2tag" , 100, 0.0, 1.0);
  hist1d["jet_csv__Emerging__GJetPredicted0To1Tag"] = new TH1F("jet_csv__Emerging__GJetPredicted0To1Tag", "jet_csv__Emerging__GJetPredicted0To1Tag" , 100, 0.0, 1.0);
  hist1d["jet_csv__Emerging__GJetPredicted1To2Tag"] = new TH1F("jet_csv__Emerging__GJetPredicted1To2Tag", "jet_csv__Emerging__GJetPredicted1To2Tag" , 100, 0.0, 1.0);
  hist1d["jet_csv__Standard__0tag"] = new TH1F("jet_csv__Standard__0tag", "jet_csv__Standard__0tag" , 100, 0.0, 1.0);
  hist1d["jet_csv__Standard__1tag"] = new TH1F("jet_csv__Standard__1tag", "jet_csv__Standard__1tag" , 100, 0.0, 1.0);
  hist1d["jet_csv__Standard__2tag"] = new TH1F("jet_csv__Standard__2tag", "jet_csv__Standard__2tag" , 100, 0.0, 1.0);
  hist1d["jet_csv__Standard__GJetPredicted0To1Tag"] = new TH1F("jet_csv__Standard__GJetPredicted0To1Tag", "jet_csv__Standard__GJetPredicted0To1Tag" , 100, 0.0, 1.0);
  hist1d["jet_csv__Standard__GJetPredicted1To2Tag"] = new TH1F("jet_csv__Standard__GJetPredicted1To2Tag", "jet_csv__Standard__GJetPredicted1To2Tag" , 100, 0.0, 1.0);
  hist1d["jet_pt__B__Emerging__0tag"] = new TH1F("jet_pt__B__Emerging__0tag", "jet_pt__B__Emerging__0tag" , 150, 0, 1500);
  hist1d["jet_pt__B__Emerging__1tag"] = new TH1F("jet_pt__B__Emerging__1tag", "jet_pt__B__Emerging__1tag" , 150, 0, 1500);
  hist1d["jet_pt__B__Emerging__2tag"] = new TH1F("jet_pt__B__Emerging__2tag", "jet_pt__B__Emerging__2tag" , 150, 0, 1500);
  hist1d["jet_pt__B__Emerging__GJetPredicted0To1Tag"] = new TH1F("jet_pt__B__Emerging__GJetPredicted0To1Tag", "jet_pt__B__Emerging__GJetPredicted0To1Tag" , 150, 0, 1500);
  hist1d["jet_pt__B__Emerging__GJetPredicted1To2Tag"] = new TH1F("jet_pt__B__Emerging__GJetPredicted1To2Tag", "jet_pt__B__Emerging__GJetPredicted1To2Tag" , 150, 0, 1500);
  hist1d["jet_pt__B__Standard__0tag"] = new TH1F("jet_pt__B__Standard__0tag", "jet_pt__B__Standard__0tag" , 150, 0, 1500);
  hist1d["jet_pt__B__Standard__1tag"] = new TH1F("jet_pt__B__Standard__1tag", "jet_pt__B__Standard__1tag" , 150, 0, 1500);
  hist1d["jet_pt__B__Standard__2tag"] = new TH1F("jet_pt__B__Standard__2tag", "jet_pt__B__Standard__2tag" , 150, 0, 1500);
  hist1d["jet_pt__B__Standard__GJetPredicted0To1Tag"] = new TH1F("jet_pt__B__Standard__GJetPredicted0To1Tag", "jet_pt__B__Standard__GJetPredicted0To1Tag" , 150, 0, 1500);
  hist1d["jet_pt__B__Standard__GJetPredicted1To2Tag"] = new TH1F("jet_pt__B__Standard__GJetPredicted1To2Tag", "jet_pt__B__Standard__GJetPredicted1To2Tag" , 150, 0, 1500);
  hist1d["jet_pt__L__Emerging__0tag"] = new TH1F("jet_pt__L__Emerging__0tag", "jet_pt__L__Emerging__0tag" , 150, 0, 1500);
  hist1d["jet_pt__L__Emerging__1tag"] = new TH1F("jet_pt__L__Emerging__1tag", "jet_pt__L__Emerging__1tag" , 150, 0, 1500);
  hist1d["jet_pt__L__Emerging__2tag"] = new TH1F("jet_pt__L__Emerging__2tag", "jet_pt__L__Emerging__2tag" , 150, 0, 1500);
  hist1d["jet_pt__L__Emerging__GJetPredicted0To1Tag"] = new TH1F("jet_pt__L__Emerging__GJetPredicted0To1Tag", "jet_pt__L__Emerging__GJetPredicted0To1Tag" , 150, 0, 1500);
  hist1d["jet_pt__L__Emerging__GJetPredicted1To2Tag"] = new TH1F("jet_pt__L__Emerging__GJetPredicted1To2Tag", "jet_pt__L__Emerging__GJetPredicted1To2Tag" , 150, 0, 1500);
  hist1d["jet_pt__L__Standard__0tag"] = new TH1F("jet_pt__L__Standard__0tag", "jet_pt__L__Standard__0tag" , 150, 0, 1500);
  hist1d["jet_pt__L__Standard__1tag"] = new TH1F("jet_pt__L__Standard__1tag", "jet_pt__L__Standard__1tag" , 150, 0, 1500);
  hist1d["jet_pt__L__Standard__2tag"] = new TH1F("jet_pt__L__Standard__2tag", "jet_pt__L__Standard__2tag" , 150, 0, 1500);
  hist1d["jet_pt__L__Standard__GJetPredicted0To1Tag"] = new TH1F("jet_pt__L__Standard__GJetPredicted0To1Tag", "jet_pt__L__Standard__GJetPredicted0To1Tag" , 150, 0, 1500);
  hist1d["jet_pt__L__Standard__GJetPredicted1To2Tag"] = new TH1F("jet_pt__L__Standard__GJetPredicted1To2Tag", "jet_pt__L__Standard__GJetPredicted1To2Tag" , 150, 0, 1500);
  hist1d["jet_eta__B__Emerging__0tag"] = new TH1F("jet_eta__B__Emerging__0tag", "jet_eta__B__Emerging__0tag" , 100, -5, 5);
  hist1d["jet_eta__B__Emerging__1tag"] = new TH1F("jet_eta__B__Emerging__1tag", "jet_eta__B__Emerging__1tag" , 100, -5, 5);
  hist1d["jet_eta__B__Emerging__2tag"] = new TH1F("jet_eta__B__Emerging__2tag", "jet_eta__B__Emerging__2tag" , 100, -5, 5);
  hist1d["jet_eta__B__Emerging__GJetPredicted0To1Tag"] = new TH1F("jet_eta__B__Emerging__GJetPredicted0To1Tag", "jet_eta__B__Emerging__GJetPredicted0To1Tag" , 100, -5, 5);
  hist1d["jet_eta__B__Emerging__GJetPredicted1To2Tag"] = new TH1F("jet_eta__B__Emerging__GJetPredicted1To2Tag", "jet_eta__B__Emerging__GJetPredicted1To2Tag" , 100, -5, 5);
  hist1d["jet_eta__B__Standard__0tag"] = new TH1F("jet_eta__B__Standard__0tag", "jet_eta__B__Standard__0tag" , 100, -5, 5);
  hist1d["jet_eta__B__Standard__1tag"] = new TH1F("jet_eta__B__Standard__1tag", "jet_eta__B__Standard__1tag" , 100, -5, 5);
  hist1d["jet_eta__B__Standard__2tag"] = new TH1F("jet_eta__B__Standard__2tag", "jet_eta__B__Standard__2tag" , 100, -5, 5);
  hist1d["jet_eta__B__Standard__GJetPredicted0To1Tag"] = new TH1F("jet_eta__B__Standard__GJetPredicted0To1Tag", "jet_eta__B__Standard__GJetPredicted0To1Tag" , 100, -5, 5);
  hist1d["jet_eta__B__Standard__GJetPredicted1To2Tag"] = new TH1F("jet_eta__B__Standard__GJetPredicted1To2Tag", "jet_eta__B__Standard__GJetPredicted1To2Tag" , 100, -5, 5);
  hist1d["jet_eta__L__Emerging__0tag"] = new TH1F("jet_eta__L__Emerging__0tag", "jet_eta__L__Emerging__0tag" , 100, -5, 5);
  hist1d["jet_eta__L__Emerging__1tag"] = new TH1F("jet_eta__L__Emerging__1tag", "jet_eta__L__Emerging__1tag" , 100, -5, 5);
  hist1d["jet_eta__L__Emerging__2tag"] = new TH1F("jet_eta__L__Emerging__2tag", "jet_eta__L__Emerging__2tag" , 100, -5, 5);
  hist1d["jet_eta__L__Emerging__GJetPredicted0To1Tag"] = new TH1F("jet_eta__L__Emerging__GJetPredicted0To1Tag", "jet_eta__L__Emerging__GJetPredicted0To1Tag" , 100, -5, 5);
  hist1d["jet_eta__L__Emerging__GJetPredicted1To2Tag"] = new TH1F("jet_eta__L__Emerging__GJetPredicted1To2Tag", "jet_eta__L__Emerging__GJetPredicted1To2Tag" , 100, -5, 5);
  hist1d["jet_eta__L__Standard__0tag"] = new TH1F("jet_eta__L__Standard__0tag", "jet_eta__L__Standard__0tag" , 100, -5, 5);
  hist1d["jet_eta__L__Standard__1tag"] = new TH1F("jet_eta__L__Standard__1tag", "jet_eta__L__Standard__1tag" , 100, -5, 5);
  hist1d["jet_eta__L__Standard__2tag"] = new TH1F("jet_eta__L__Standard__2tag", "jet_eta__L__Standard__2tag" , 100, -5, 5);
  hist1d["jet_eta__L__Standard__GJetPredicted0To1Tag"] = new TH1F("jet_eta__L__Standard__GJetPredicted0To1Tag", "jet_eta__L__Standard__GJetPredicted0To1Tag" , 100, -5, 5);
  hist1d["jet_eta__L__Standard__GJetPredicted1To2Tag"] = new TH1F("jet_eta__L__Standard__GJetPredicted1To2Tag", "jet_eta__L__Standard__GJetPredicted1To2Tag" , 100, -5, 5);
  hist1d["jet_phi__B__Emerging__0tag"] = new TH1F("jet_phi__B__Emerging__0tag", "jet_phi__B__Emerging__0tag" , 100, -5, 5);
  hist1d["jet_phi__B__Emerging__1tag"] = new TH1F("jet_phi__B__Emerging__1tag", "jet_phi__B__Emerging__1tag" , 100, -5, 5);
  hist1d["jet_phi__B__Emerging__2tag"] = new TH1F("jet_phi__B__Emerging__2tag", "jet_phi__B__Emerging__2tag" , 100, -5, 5);
  hist1d["jet_phi__B__Emerging__GJetPredicted0To1Tag"] = new TH1F("jet_phi__B__Emerging__GJetPredicted0To1Tag", "jet_phi__B__Emerging__GJetPredicted0To1Tag" , 100, -5, 5);
  hist1d["jet_phi__B__Emerging__GJetPredicted1To2Tag"] = new TH1F("jet_phi__B__Emerging__GJetPredicted1To2Tag", "jet_phi__B__Emerging__GJetPredicted1To2Tag" , 100, -5, 5);
  hist1d["jet_phi__B__Standard__0tag"] = new TH1F("jet_phi__B__Standard__0tag", "jet_phi__B__Standard__0tag" , 100, -5, 5);
  hist1d["jet_phi__B__Standard__1tag"] = new TH1F("jet_phi__B__Standard__1tag", "jet_phi__B__Standard__1tag" , 100, -5, 5);
  hist1d["jet_phi__B__Standard__2tag"] = new TH1F("jet_phi__B__Standard__2tag", "jet_phi__B__Standard__2tag" , 100, -5, 5);
  hist1d["jet_phi__B__Standard__GJetPredicted0To1Tag"] = new TH1F("jet_phi__B__Standard__GJetPredicted0To1Tag", "jet_phi__B__Standard__GJetPredicted0To1Tag" , 100, -5, 5);
  hist1d["jet_phi__B__Standard__GJetPredicted1To2Tag"] = new TH1F("jet_phi__B__Standard__GJetPredicted1To2Tag", "jet_phi__B__Standard__GJetPredicted1To2Tag" , 100, -5, 5);
  hist1d["jet_phi__L__Emerging__0tag"] = new TH1F("jet_phi__L__Emerging__0tag", "jet_phi__L__Emerging__0tag" , 100, -5, 5);
  hist1d["jet_phi__L__Emerging__1tag"] = new TH1F("jet_phi__L__Emerging__1tag", "jet_phi__L__Emerging__1tag" , 100, -5, 5);
  hist1d["jet_phi__L__Emerging__2tag"] = new TH1F("jet_phi__L__Emerging__2tag", "jet_phi__L__Emerging__2tag" , 100, -5, 5);
  hist1d["jet_phi__L__Emerging__GJetPredicted0To1Tag"] = new TH1F("jet_phi__L__Emerging__GJetPredicted0To1Tag", "jet_phi__L__Emerging__GJetPredicted0To1Tag" , 100, -5, 5);
  hist1d["jet_phi__L__Emerging__GJetPredicted1To2Tag"] = new TH1F("jet_phi__L__Emerging__GJetPredicted1To2Tag", "jet_phi__L__Emerging__GJetPredicted1To2Tag" , 100, -5, 5);
  hist1d["jet_phi__L__Standard__0tag"] = new TH1F("jet_phi__L__Standard__0tag", "jet_phi__L__Standard__0tag" , 100, -5, 5);
  hist1d["jet_phi__L__Standard__1tag"] = new TH1F("jet_phi__L__Standard__1tag", "jet_phi__L__Standard__1tag" , 100, -5, 5);
  hist1d["jet_phi__L__Standard__2tag"] = new TH1F("jet_phi__L__Standard__2tag", "jet_phi__L__Standard__2tag" , 100, -5, 5);
  hist1d["jet_phi__L__Standard__GJetPredicted0To1Tag"] = new TH1F("jet_phi__L__Standard__GJetPredicted0To1Tag", "jet_phi__L__Standard__GJetPredicted0To1Tag" , 100, -5, 5);
  hist1d["jet_phi__L__Standard__GJetPredicted1To2Tag"] = new TH1F("jet_phi__L__Standard__GJetPredicted1To2Tag", "jet_phi__L__Standard__GJetPredicted1To2Tag" , 100, -5, 5);
  hist1d["jet_nTrack__B__Emerging__0tag"] = new TH1F("jet_nTrack__B__Emerging__0tag", "jet_nTrack__B__Emerging__0tag" , 100, 0.0, 100);
  hist1d["jet_nTrack__B__Emerging__1tag"] = new TH1F("jet_nTrack__B__Emerging__1tag", "jet_nTrack__B__Emerging__1tag" , 100, 0.0, 100);
  hist1d["jet_nTrack__B__Emerging__2tag"] = new TH1F("jet_nTrack__B__Emerging__2tag", "jet_nTrack__B__Emerging__2tag" , 100, 0.0, 100);
  hist1d["jet_nTrack__B__Emerging__GJetPredicted0To1Tag"] = new TH1F("jet_nTrack__B__Emerging__GJetPredicted0To1Tag", "jet_nTrack__B__Emerging__GJetPredicted0To1Tag" , 100, 0.0, 100);
  hist1d["jet_nTrack__B__Emerging__GJetPredicted1To2Tag"] = new TH1F("jet_nTrack__B__Emerging__GJetPredicted1To2Tag", "jet_nTrack__B__Emerging__GJetPredicted1To2Tag" , 100, 0.0, 100);
  hist1d["jet_nTrack__B__Standard__0tag"] = new TH1F("jet_nTrack__B__Standard__0tag", "jet_nTrack__B__Standard__0tag" , 100, 0.0, 100);
  hist1d["jet_nTrack__B__Standard__1tag"] = new TH1F("jet_nTrack__B__Standard__1tag", "jet_nTrack__B__Standard__1tag" , 100, 0.0, 100);
  hist1d["jet_nTrack__B__Standard__2tag"] = new TH1F("jet_nTrack__B__Standard__2tag", "jet_nTrack__B__Standard__2tag" , 100, 0.0, 100);
  hist1d["jet_nTrack__B__Standard__GJetPredicted0To1Tag"] = new TH1F("jet_nTrack__B__Standard__GJetPredicted0To1Tag", "jet_nTrack__B__Standard__GJetPredicted0To1Tag" , 100, 0.0, 100);
  hist1d["jet_nTrack__B__Standard__GJetPredicted1To2Tag"] = new TH1F("jet_nTrack__B__Standard__GJetPredicted1To2Tag", "jet_nTrack__B__Standard__GJetPredicted1To2Tag" , 100, 0.0, 100);
  hist1d["jet_nTrack__L__Emerging__0tag"] = new TH1F("jet_nTrack__L__Emerging__0tag", "jet_nTrack__L__Emerging__0tag" , 100, 0.0, 100);
  hist1d["jet_nTrack__L__Emerging__1tag"] = new TH1F("jet_nTrack__L__Emerging__1tag", "jet_nTrack__L__Emerging__1tag" , 100, 0.0, 100);
  hist1d["jet_nTrack__L__Emerging__2tag"] = new TH1F("jet_nTrack__L__Emerging__2tag", "jet_nTrack__L__Emerging__2tag" , 100, 0.0, 100);
  hist1d["jet_nTrack__L__Emerging__GJetPredicted0To1Tag"] = new TH1F("jet_nTrack__L__Emerging__GJetPredicted0To1Tag", "jet_nTrack__L__Emerging__GJetPredicted0To1Tag" , 100, 0.0, 100);
  hist1d["jet_nTrack__L__Emerging__GJetPredicted1To2Tag"] = new TH1F("jet_nTrack__L__Emerging__GJetPredicted1To2Tag", "jet_nTrack__L__Emerging__GJetPredicted1To2Tag" , 100, 0.0, 100);
  hist1d["jet_nTrack__L__Standard__0tag"] = new TH1F("jet_nTrack__L__Standard__0tag", "jet_nTrack__L__Standard__0tag" , 100, 0.0, 100);
  hist1d["jet_nTrack__L__Standard__1tag"] = new TH1F("jet_nTrack__L__Standard__1tag", "jet_nTrack__L__Standard__1tag" , 100, 0.0, 100);
  hist1d["jet_nTrack__L__Standard__2tag"] = new TH1F("jet_nTrack__L__Standard__2tag", "jet_nTrack__L__Standard__2tag" , 100, 0.0, 100);
  hist1d["jet_nTrack__L__Standard__GJetPredicted0To1Tag"] = new TH1F("jet_nTrack__L__Standard__GJetPredicted0To1Tag", "jet_nTrack__L__Standard__GJetPredicted0To1Tag" , 100, 0.0, 100);
  hist1d["jet_nTrack__L__Standard__GJetPredicted1To2Tag"] = new TH1F("jet_nTrack__L__Standard__GJetPredicted1To2Tag", "jet_nTrack__L__Standard__GJetPredicted1To2Tag" , 100, 0.0, 100);
  hist1d["jet_nTrackPostCut__B__Emerging__0tag"] = new TH1F("jet_nTrackPostCut__B__Emerging__0tag", "jet_nTrackPostCut__B__Emerging__0tag" , 100, 0.0, 100);
  hist1d["jet_nTrackPostCut__B__Emerging__1tag"] = new TH1F("jet_nTrackPostCut__B__Emerging__1tag", "jet_nTrackPostCut__B__Emerging__1tag" , 100, 0.0, 100);
  hist1d["jet_nTrackPostCut__B__Emerging__2tag"] = new TH1F("jet_nTrackPostCut__B__Emerging__2tag", "jet_nTrackPostCut__B__Emerging__2tag" , 100, 0.0, 100);
  hist1d["jet_nTrackPostCut__B__Emerging__GJetPredicted0To1Tag"] = new TH1F("jet_nTrackPostCut__B__Emerging__GJetPredicted0To1Tag", "jet_nTrackPostCut__B__Emerging__GJetPredicted0To1Tag" , 100, 0.0, 100);
  hist1d["jet_nTrackPostCut__B__Emerging__GJetPredicted1To2Tag"] = new TH1F("jet_nTrackPostCut__B__Emerging__GJetPredicted1To2Tag", "jet_nTrackPostCut__B__Emerging__GJetPredicted1To2Tag" , 100, 0.0, 100);
  hist1d["jet_nTrackPostCut__B__Standard__0tag"] = new TH1F("jet_nTrackPostCut__B__Standard__0tag", "jet_nTrackPostCut__B__Standard__0tag" , 100, 0.0, 100);
  hist1d["jet_nTrackPostCut__B__Standard__1tag"] = new TH1F("jet_nTrackPostCut__B__Standard__1tag", "jet_nTrackPostCut__B__Standard__1tag" , 100, 0.0, 100);
  hist1d["jet_nTrackPostCut__B__Standard__2tag"] = new TH1F("jet_nTrackPostCut__B__Standard__2tag", "jet_nTrackPostCut__B__Standard__2tag" , 100, 0.0, 100);
  hist1d["jet_nTrackPostCut__B__Standard__GJetPredicted0To1Tag"] = new TH1F("jet_nTrackPostCut__B__Standard__GJetPredicted0To1Tag", "jet_nTrackPostCut__B__Standard__GJetPredicted0To1Tag" , 100, 0.0, 100);
  hist1d["jet_nTrackPostCut__B__Standard__GJetPredicted1To2Tag"] = new TH1F("jet_nTrackPostCut__B__Standard__GJetPredicted1To2Tag", "jet_nTrackPostCut__B__Standard__GJetPredicted1To2Tag" , 100, 0.0, 100);
  hist1d["jet_nTrackPostCut__L__Emerging__0tag"] = new TH1F("jet_nTrackPostCut__L__Emerging__0tag", "jet_nTrackPostCut__L__Emerging__0tag" , 100, 0.0, 100);
  hist1d["jet_nTrackPostCut__L__Emerging__1tag"] = new TH1F("jet_nTrackPostCut__L__Emerging__1tag", "jet_nTrackPostCut__L__Emerging__1tag" , 100, 0.0, 100);
  hist1d["jet_nTrackPostCut__L__Emerging__2tag"] = new TH1F("jet_nTrackPostCut__L__Emerging__2tag", "jet_nTrackPostCut__L__Emerging__2tag" , 100, 0.0, 100);
  hist1d["jet_nTrackPostCut__L__Emerging__GJetPredicted0To1Tag"] = new TH1F("jet_nTrackPostCut__L__Emerging__GJetPredicted0To1Tag", "jet_nTrackPostCut__L__Emerging__GJetPredicted0To1Tag" , 100, 0.0, 100);
  hist1d["jet_nTrackPostCut__L__Emerging__GJetPredicted1To2Tag"] = new TH1F("jet_nTrackPostCut__L__Emerging__GJetPredicted1To2Tag", "jet_nTrackPostCut__L__Emerging__GJetPredicted1To2Tag" , 100, 0.0, 100);
  hist1d["jet_nTrackPostCut__L__Standard__0tag"] = new TH1F("jet_nTrackPostCut__L__Standard__0tag", "jet_nTrackPostCut__L__Standard__0tag" , 100, 0.0, 100);
  hist1d["jet_nTrackPostCut__L__Standard__1tag"] = new TH1F("jet_nTrackPostCut__L__Standard__1tag", "jet_nTrackPostCut__L__Standard__1tag" , 100, 0.0, 100);
  hist1d["jet_nTrackPostCut__L__Standard__2tag"] = new TH1F("jet_nTrackPostCut__L__Standard__2tag", "jet_nTrackPostCut__L__Standard__2tag" , 100, 0.0, 100);
  hist1d["jet_nTrackPostCut__L__Standard__GJetPredicted0To1Tag"] = new TH1F("jet_nTrackPostCut__L__Standard__GJetPredicted0To1Tag", "jet_nTrackPostCut__L__Standard__GJetPredicted0To1Tag" , 100, 0.0, 100);
  hist1d["jet_nTrackPostCut__L__Standard__GJetPredicted1To2Tag"] = new TH1F("jet_nTrackPostCut__L__Standard__GJetPredicted1To2Tag", "jet_nTrackPostCut__L__Standard__GJetPredicted1To2Tag" , 100, 0.0, 100);
  hist1d["jet_csv__B__Emerging__0tag"] = new TH1F("jet_csv__B__Emerging__0tag", "jet_csv__B__Emerging__0tag" , 100, 0.0, 1.0);
  hist1d["jet_csv__B__Emerging__1tag"] = new TH1F("jet_csv__B__Emerging__1tag", "jet_csv__B__Emerging__1tag" , 100, 0.0, 1.0);
  hist1d["jet_csv__B__Emerging__2tag"] = new TH1F("jet_csv__B__Emerging__2tag", "jet_csv__B__Emerging__2tag" , 100, 0.0, 1.0);
  hist1d["jet_csv__B__Emerging__GJetPredicted0To1Tag"] = new TH1F("jet_csv__B__Emerging__GJetPredicted0To1Tag", "jet_csv__B__Emerging__GJetPredicted0To1Tag" , 100, 0.0, 1.0);
  hist1d["jet_csv__B__Emerging__GJetPredicted1To2Tag"] = new TH1F("jet_csv__B__Emerging__GJetPredicted1To2Tag", "jet_csv__B__Emerging__GJetPredicted1To2Tag" , 100, 0.0, 1.0);
  hist1d["jet_csv__B__Standard__0tag"] = new TH1F("jet_csv__B__Standard__0tag", "jet_csv__B__Standard__0tag" , 100, 0.0, 1.0);
  hist1d["jet_csv__B__Standard__1tag"] = new TH1F("jet_csv__B__Standard__1tag", "jet_csv__B__Standard__1tag" , 100, 0.0, 1.0);
  hist1d["jet_csv__B__Standard__2tag"] = new TH1F("jet_csv__B__Standard__2tag", "jet_csv__B__Standard__2tag" , 100, 0.0, 1.0);
  hist1d["jet_csv__B__Standard__GJetPredicted0To1Tag"] = new TH1F("jet_csv__B__Standard__GJetPredicted0To1Tag", "jet_csv__B__Standard__GJetPredicted0To1Tag" , 100, 0.0, 1.0);
  hist1d["jet_csv__B__Standard__GJetPredicted1To2Tag"] = new TH1F("jet_csv__B__Standard__GJetPredicted1To2Tag", "jet_csv__B__Standard__GJetPredicted1To2Tag" , 100, 0.0, 1.0);
  hist1d["jet_csv__L__Emerging__0tag"] = new TH1F("jet_csv__L__Emerging__0tag", "jet_csv__L__Emerging__0tag" , 100, 0.0, 1.0);
  hist1d["jet_csv__L__Emerging__1tag"] = new TH1F("jet_csv__L__Emerging__1tag", "jet_csv__L__Emerging__1tag" , 100, 0.0, 1.0);
  hist1d["jet_csv__L__Emerging__2tag"] = new TH1F("jet_csv__L__Emerging__2tag", "jet_csv__L__Emerging__2tag" , 100, 0.0, 1.0);
  hist1d["jet_csv__L__Emerging__GJetPredicted0To1Tag"] = new TH1F("jet_csv__L__Emerging__GJetPredicted0To1Tag", "jet_csv__L__Emerging__GJetPredicted0To1Tag" , 100, 0.0, 1.0);
  hist1d["jet_csv__L__Emerging__GJetPredicted1To2Tag"] = new TH1F("jet_csv__L__Emerging__GJetPredicted1To2Tag", "jet_csv__L__Emerging__GJetPredicted1To2Tag" , 100, 0.0, 1.0);
  hist1d["jet_csv__L__Standard__0tag"] = new TH1F("jet_csv__L__Standard__0tag", "jet_csv__L__Standard__0tag" , 100, 0.0, 1.0);
  hist1d["jet_csv__L__Standard__1tag"] = new TH1F("jet_csv__L__Standard__1tag", "jet_csv__L__Standard__1tag" , 100, 0.0, 1.0);
  hist1d["jet_csv__L__Standard__2tag"] = new TH1F("jet_csv__L__Standard__2tag", "jet_csv__L__Standard__2tag" , 100, 0.0, 1.0);
  hist1d["jet_csv__L__Standard__GJetPredicted0To1Tag"] = new TH1F("jet_csv__L__Standard__GJetPredicted0To1Tag", "jet_csv__L__Standard__GJetPredicted0To1Tag" , 100, 0.0, 1.0);
  hist1d["jet_csv__L__Standard__GJetPredicted1To2Tag"] = new TH1F("jet_csv__L__Standard__GJetPredicted1To2Tag", "jet_csv__L__Standard__GJetPredicted1To2Tag" , 100, 0.0, 1.0);
    //[[[end]]]
}

EmJetHistos::~EmJetHistos()
{
  for (const auto & kv : hist1d) {
    delete kv.second;
  }
}

int
EmJetHistos::GetHistoIndex(string name)
{
  /*[[[cog
    mod.generate_histo_index()
    ]]]*/
  if (name=="ht") return 0;
  if (name=="jet_pt") return 1;
  if (name=="jet_eta") return 2;
  if (name=="jet_phi") return 3;
  if (name=="jet_nTrack") return 4;
  if (name=="jet_nTrackPostCut") return 5;
  if (name=="jet_csv") return 6;
  if (name=="nJet_tag") return 7;
  if (name=="n1tag") return 8;
  if (name=="n2tag") return 9;
  if (name=="n1tag__0") return 10;
  if (name=="n1tag__1") return 11;
  if (name=="n1tag__2") return 12;
  if (name=="n1tag__3") return 13;
  if (name=="n1tag__4") return 14;
  if (name=="n1tag__5") return 15;
  if (name=="n1tag__6") return 16;
  if (name=="n1tag__7") return 17;
  if (name=="n1tag__8") return 18;
  if (name=="n1tag__9") return 19;
  if (name=="n2tag__0") return 20;
  if (name=="n2tag__1") return 21;
  if (name=="n2tag__2") return 22;
  if (name=="n2tag__3") return 23;
  if (name=="n2tag__4") return 24;
  if (name=="n2tag__5") return 25;
  if (name=="n2tag__6") return 26;
  if (name=="n2tag__7") return 27;
  if (name=="n2tag__8") return 28;
  if (name=="n2tag__9") return 29;
  if (name=="jet_pt__B") return 30;
  if (name=="jet_pt__L") return 31;
  if (name=="jet_eta__B") return 32;
  if (name=="jet_eta__L") return 33;
  if (name=="jet_phi__B") return 34;
  if (name=="jet_phi__L") return 35;
  if (name=="jet_nTrack__B") return 36;
  if (name=="jet_nTrack__L") return 37;
  if (name=="jet_nTrackPostCut__B") return 38;
  if (name=="jet_nTrackPostCut__L") return 39;
  if (name=="jet_csv__B") return 40;
  if (name=="jet_csv__L") return 41;
  if (name=="jet_pt__Emerging") return 42;
  if (name=="jet_pt__Standard") return 43;
  if (name=="jet_eta__Emerging") return 44;
  if (name=="jet_eta__Standard") return 45;
  if (name=="jet_phi__Emerging") return 46;
  if (name=="jet_phi__Standard") return 47;
  if (name=="jet_nTrack__Emerging") return 48;
  if (name=="jet_nTrack__Standard") return 49;
  if (name=="jet_nTrackPostCut__Emerging") return 50;
  if (name=="jet_nTrackPostCut__Standard") return 51;
  if (name=="jet_csv__Emerging") return 52;
  if (name=="jet_csv__Standard") return 53;
  if (name=="jet_pt__B__Emerging") return 54;
  if (name=="jet_pt__B__Standard") return 55;
  if (name=="jet_pt__L__Emerging") return 56;
  if (name=="jet_pt__L__Standard") return 57;
  if (name=="jet_eta__B__Emerging") return 58;
  if (name=="jet_eta__B__Standard") return 59;
  if (name=="jet_eta__L__Emerging") return 60;
  if (name=="jet_eta__L__Standard") return 61;
  if (name=="jet_phi__B__Emerging") return 62;
  if (name=="jet_phi__B__Standard") return 63;
  if (name=="jet_phi__L__Emerging") return 64;
  if (name=="jet_phi__L__Standard") return 65;
  if (name=="jet_nTrack__B__Emerging") return 66;
  if (name=="jet_nTrack__B__Standard") return 67;
  if (name=="jet_nTrack__L__Emerging") return 68;
  if (name=="jet_nTrack__L__Standard") return 69;
  if (name=="jet_nTrackPostCut__B__Emerging") return 70;
  if (name=="jet_nTrackPostCut__B__Standard") return 71;
  if (name=="jet_nTrackPostCut__L__Emerging") return 72;
  if (name=="jet_nTrackPostCut__L__Standard") return 73;
  if (name=="jet_csv__B__Emerging") return 74;
  if (name=="jet_csv__B__Standard") return 75;
  if (name=="jet_csv__L__Emerging") return 76;
  if (name=="jet_csv__L__Standard") return 77;
  if (name=="ht__0tag") return 78;
  if (name=="ht__1tag") return 79;
  if (name=="ht__2tag") return 80;
  if (name=="ht__GJetPredicted0To1Tag") return 81;
  if (name=="ht__GJetPredicted1To2Tag") return 82;
  if (name=="jet_pt__0tag") return 83;
  if (name=="jet_pt__1tag") return 84;
  if (name=="jet_pt__2tag") return 85;
  if (name=="jet_pt__GJetPredicted0To1Tag") return 86;
  if (name=="jet_pt__GJetPredicted1To2Tag") return 87;
  if (name=="jet_eta__0tag") return 88;
  if (name=="jet_eta__1tag") return 89;
  if (name=="jet_eta__2tag") return 90;
  if (name=="jet_eta__GJetPredicted0To1Tag") return 91;
  if (name=="jet_eta__GJetPredicted1To2Tag") return 92;
  if (name=="jet_phi__0tag") return 93;
  if (name=="jet_phi__1tag") return 94;
  if (name=="jet_phi__2tag") return 95;
  if (name=="jet_phi__GJetPredicted0To1Tag") return 96;
  if (name=="jet_phi__GJetPredicted1To2Tag") return 97;
  if (name=="jet_nTrack__0tag") return 98;
  if (name=="jet_nTrack__1tag") return 99;
  if (name=="jet_nTrack__2tag") return 100;
  if (name=="jet_nTrack__GJetPredicted0To1Tag") return 101;
  if (name=="jet_nTrack__GJetPredicted1To2Tag") return 102;
  if (name=="jet_nTrackPostCut__0tag") return 103;
  if (name=="jet_nTrackPostCut__1tag") return 104;
  if (name=="jet_nTrackPostCut__2tag") return 105;
  if (name=="jet_nTrackPostCut__GJetPredicted0To1Tag") return 106;
  if (name=="jet_nTrackPostCut__GJetPredicted1To2Tag") return 107;
  if (name=="jet_csv__0tag") return 108;
  if (name=="jet_csv__1tag") return 109;
  if (name=="jet_csv__2tag") return 110;
  if (name=="jet_csv__GJetPredicted0To1Tag") return 111;
  if (name=="jet_csv__GJetPredicted1To2Tag") return 112;
  if (name=="jet_pt__B__0tag") return 113;
  if (name=="jet_pt__B__1tag") return 114;
  if (name=="jet_pt__B__2tag") return 115;
  if (name=="jet_pt__B__GJetPredicted0To1Tag") return 116;
  if (name=="jet_pt__B__GJetPredicted1To2Tag") return 117;
  if (name=="jet_pt__L__0tag") return 118;
  if (name=="jet_pt__L__1tag") return 119;
  if (name=="jet_pt__L__2tag") return 120;
  if (name=="jet_pt__L__GJetPredicted0To1Tag") return 121;
  if (name=="jet_pt__L__GJetPredicted1To2Tag") return 122;
  if (name=="jet_eta__B__0tag") return 123;
  if (name=="jet_eta__B__1tag") return 124;
  if (name=="jet_eta__B__2tag") return 125;
  if (name=="jet_eta__B__GJetPredicted0To1Tag") return 126;
  if (name=="jet_eta__B__GJetPredicted1To2Tag") return 127;
  if (name=="jet_eta__L__0tag") return 128;
  if (name=="jet_eta__L__1tag") return 129;
  if (name=="jet_eta__L__2tag") return 130;
  if (name=="jet_eta__L__GJetPredicted0To1Tag") return 131;
  if (name=="jet_eta__L__GJetPredicted1To2Tag") return 132;
  if (name=="jet_phi__B__0tag") return 133;
  if (name=="jet_phi__B__1tag") return 134;
  if (name=="jet_phi__B__2tag") return 135;
  if (name=="jet_phi__B__GJetPredicted0To1Tag") return 136;
  if (name=="jet_phi__B__GJetPredicted1To2Tag") return 137;
  if (name=="jet_phi__L__0tag") return 138;
  if (name=="jet_phi__L__1tag") return 139;
  if (name=="jet_phi__L__2tag") return 140;
  if (name=="jet_phi__L__GJetPredicted0To1Tag") return 141;
  if (name=="jet_phi__L__GJetPredicted1To2Tag") return 142;
  if (name=="jet_nTrack__B__0tag") return 143;
  if (name=="jet_nTrack__B__1tag") return 144;
  if (name=="jet_nTrack__B__2tag") return 145;
  if (name=="jet_nTrack__B__GJetPredicted0To1Tag") return 146;
  if (name=="jet_nTrack__B__GJetPredicted1To2Tag") return 147;
  if (name=="jet_nTrack__L__0tag") return 148;
  if (name=="jet_nTrack__L__1tag") return 149;
  if (name=="jet_nTrack__L__2tag") return 150;
  if (name=="jet_nTrack__L__GJetPredicted0To1Tag") return 151;
  if (name=="jet_nTrack__L__GJetPredicted1To2Tag") return 152;
  if (name=="jet_nTrackPostCut__B__0tag") return 153;
  if (name=="jet_nTrackPostCut__B__1tag") return 154;
  if (name=="jet_nTrackPostCut__B__2tag") return 155;
  if (name=="jet_nTrackPostCut__B__GJetPredicted0To1Tag") return 156;
  if (name=="jet_nTrackPostCut__B__GJetPredicted1To2Tag") return 157;
  if (name=="jet_nTrackPostCut__L__0tag") return 158;
  if (name=="jet_nTrackPostCut__L__1tag") return 159;
  if (name=="jet_nTrackPostCut__L__2tag") return 160;
  if (name=="jet_nTrackPostCut__L__GJetPredicted0To1Tag") return 161;
  if (name=="jet_nTrackPostCut__L__GJetPredicted1To2Tag") return 162;
  if (name=="jet_csv__B__0tag") return 163;
  if (name=="jet_csv__B__1tag") return 164;
  if (name=="jet_csv__B__2tag") return 165;
  if (name=="jet_csv__B__GJetPredicted0To1Tag") return 166;
  if (name=="jet_csv__B__GJetPredicted1To2Tag") return 167;
  if (name=="jet_csv__L__0tag") return 168;
  if (name=="jet_csv__L__1tag") return 169;
  if (name=="jet_csv__L__2tag") return 170;
  if (name=="jet_csv__L__GJetPredicted0To1Tag") return 171;
  if (name=="jet_csv__L__GJetPredicted1To2Tag") return 172;
  if (name=="jet_pt__Emerging__0tag") return 173;
  if (name=="jet_pt__Emerging__1tag") return 174;
  if (name=="jet_pt__Emerging__2tag") return 175;
  if (name=="jet_pt__Emerging__GJetPredicted0To1Tag") return 176;
  if (name=="jet_pt__Emerging__GJetPredicted1To2Tag") return 177;
  if (name=="jet_pt__Standard__0tag") return 178;
  if (name=="jet_pt__Standard__1tag") return 179;
  if (name=="jet_pt__Standard__2tag") return 180;
  if (name=="jet_pt__Standard__GJetPredicted0To1Tag") return 181;
  if (name=="jet_pt__Standard__GJetPredicted1To2Tag") return 182;
  if (name=="jet_eta__Emerging__0tag") return 183;
  if (name=="jet_eta__Emerging__1tag") return 184;
  if (name=="jet_eta__Emerging__2tag") return 185;
  if (name=="jet_eta__Emerging__GJetPredicted0To1Tag") return 186;
  if (name=="jet_eta__Emerging__GJetPredicted1To2Tag") return 187;
  if (name=="jet_eta__Standard__0tag") return 188;
  if (name=="jet_eta__Standard__1tag") return 189;
  if (name=="jet_eta__Standard__2tag") return 190;
  if (name=="jet_eta__Standard__GJetPredicted0To1Tag") return 191;
  if (name=="jet_eta__Standard__GJetPredicted1To2Tag") return 192;
  if (name=="jet_phi__Emerging__0tag") return 193;
  if (name=="jet_phi__Emerging__1tag") return 194;
  if (name=="jet_phi__Emerging__2tag") return 195;
  if (name=="jet_phi__Emerging__GJetPredicted0To1Tag") return 196;
  if (name=="jet_phi__Emerging__GJetPredicted1To2Tag") return 197;
  if (name=="jet_phi__Standard__0tag") return 198;
  if (name=="jet_phi__Standard__1tag") return 199;
  if (name=="jet_phi__Standard__2tag") return 200;
  if (name=="jet_phi__Standard__GJetPredicted0To1Tag") return 201;
  if (name=="jet_phi__Standard__GJetPredicted1To2Tag") return 202;
  if (name=="jet_nTrack__Emerging__0tag") return 203;
  if (name=="jet_nTrack__Emerging__1tag") return 204;
  if (name=="jet_nTrack__Emerging__2tag") return 205;
  if (name=="jet_nTrack__Emerging__GJetPredicted0To1Tag") return 206;
  if (name=="jet_nTrack__Emerging__GJetPredicted1To2Tag") return 207;
  if (name=="jet_nTrack__Standard__0tag") return 208;
  if (name=="jet_nTrack__Standard__1tag") return 209;
  if (name=="jet_nTrack__Standard__2tag") return 210;
  if (name=="jet_nTrack__Standard__GJetPredicted0To1Tag") return 211;
  if (name=="jet_nTrack__Standard__GJetPredicted1To2Tag") return 212;
  if (name=="jet_nTrackPostCut__Emerging__0tag") return 213;
  if (name=="jet_nTrackPostCut__Emerging__1tag") return 214;
  if (name=="jet_nTrackPostCut__Emerging__2tag") return 215;
  if (name=="jet_nTrackPostCut__Emerging__GJetPredicted0To1Tag") return 216;
  if (name=="jet_nTrackPostCut__Emerging__GJetPredicted1To2Tag") return 217;
  if (name=="jet_nTrackPostCut__Standard__0tag") return 218;
  if (name=="jet_nTrackPostCut__Standard__1tag") return 219;
  if (name=="jet_nTrackPostCut__Standard__2tag") return 220;
  if (name=="jet_nTrackPostCut__Standard__GJetPredicted0To1Tag") return 221;
  if (name=="jet_nTrackPostCut__Standard__GJetPredicted1To2Tag") return 222;
  if (name=="jet_csv__Emerging__0tag") return 223;
  if (name=="jet_csv__Emerging__1tag") return 224;
  if (name=="jet_csv__Emerging__2tag") return 225;
  if (name=="jet_csv__Emerging__GJetPredicted0To1Tag") return 226;
  if (name=="jet_csv__Emerging__GJetPredicted1To2Tag") return 227;
  if (name=="jet_csv__Standard__0tag") return 228;
  if (name=="jet_csv__Standard__1tag") return 229;
  if (name=="jet_csv__Standard__2tag") return 230;
  if (name=="jet_csv__Standard__GJetPredicted0To1Tag") return 231;
  if (name=="jet_csv__Standard__GJetPredicted1To2Tag") return 232;
  if (name=="jet_pt__B__Emerging__0tag") return 233;
  if (name=="jet_pt__B__Emerging__1tag") return 234;
  if (name=="jet_pt__B__Emerging__2tag") return 235;
  if (name=="jet_pt__B__Emerging__GJetPredicted0To1Tag") return 236;
  if (name=="jet_pt__B__Emerging__GJetPredicted1To2Tag") return 237;
  if (name=="jet_pt__B__Standard__0tag") return 238;
  if (name=="jet_pt__B__Standard__1tag") return 239;
  if (name=="jet_pt__B__Standard__2tag") return 240;
  if (name=="jet_pt__B__Standard__GJetPredicted0To1Tag") return 241;
  if (name=="jet_pt__B__Standard__GJetPredicted1To2Tag") return 242;
  if (name=="jet_pt__L__Emerging__0tag") return 243;
  if (name=="jet_pt__L__Emerging__1tag") return 244;
  if (name=="jet_pt__L__Emerging__2tag") return 245;
  if (name=="jet_pt__L__Emerging__GJetPredicted0To1Tag") return 246;
  if (name=="jet_pt__L__Emerging__GJetPredicted1To2Tag") return 247;
  if (name=="jet_pt__L__Standard__0tag") return 248;
  if (name=="jet_pt__L__Standard__1tag") return 249;
  if (name=="jet_pt__L__Standard__2tag") return 250;
  if (name=="jet_pt__L__Standard__GJetPredicted0To1Tag") return 251;
  if (name=="jet_pt__L__Standard__GJetPredicted1To2Tag") return 252;
  if (name=="jet_eta__B__Emerging__0tag") return 253;
  if (name=="jet_eta__B__Emerging__1tag") return 254;
  if (name=="jet_eta__B__Emerging__2tag") return 255;
  if (name=="jet_eta__B__Emerging__GJetPredicted0To1Tag") return 256;
  if (name=="jet_eta__B__Emerging__GJetPredicted1To2Tag") return 257;
  if (name=="jet_eta__B__Standard__0tag") return 258;
  if (name=="jet_eta__B__Standard__1tag") return 259;
  if (name=="jet_eta__B__Standard__2tag") return 260;
  if (name=="jet_eta__B__Standard__GJetPredicted0To1Tag") return 261;
  if (name=="jet_eta__B__Standard__GJetPredicted1To2Tag") return 262;
  if (name=="jet_eta__L__Emerging__0tag") return 263;
  if (name=="jet_eta__L__Emerging__1tag") return 264;
  if (name=="jet_eta__L__Emerging__2tag") return 265;
  if (name=="jet_eta__L__Emerging__GJetPredicted0To1Tag") return 266;
  if (name=="jet_eta__L__Emerging__GJetPredicted1To2Tag") return 267;
  if (name=="jet_eta__L__Standard__0tag") return 268;
  if (name=="jet_eta__L__Standard__1tag") return 269;
  if (name=="jet_eta__L__Standard__2tag") return 270;
  if (name=="jet_eta__L__Standard__GJetPredicted0To1Tag") return 271;
  if (name=="jet_eta__L__Standard__GJetPredicted1To2Tag") return 272;
  if (name=="jet_phi__B__Emerging__0tag") return 273;
  if (name=="jet_phi__B__Emerging__1tag") return 274;
  if (name=="jet_phi__B__Emerging__2tag") return 275;
  if (name=="jet_phi__B__Emerging__GJetPredicted0To1Tag") return 276;
  if (name=="jet_phi__B__Emerging__GJetPredicted1To2Tag") return 277;
  if (name=="jet_phi__B__Standard__0tag") return 278;
  if (name=="jet_phi__B__Standard__1tag") return 279;
  if (name=="jet_phi__B__Standard__2tag") return 280;
  if (name=="jet_phi__B__Standard__GJetPredicted0To1Tag") return 281;
  if (name=="jet_phi__B__Standard__GJetPredicted1To2Tag") return 282;
  if (name=="jet_phi__L__Emerging__0tag") return 283;
  if (name=="jet_phi__L__Emerging__1tag") return 284;
  if (name=="jet_phi__L__Emerging__2tag") return 285;
  if (name=="jet_phi__L__Emerging__GJetPredicted0To1Tag") return 286;
  if (name=="jet_phi__L__Emerging__GJetPredicted1To2Tag") return 287;
  if (name=="jet_phi__L__Standard__0tag") return 288;
  if (name=="jet_phi__L__Standard__1tag") return 289;
  if (name=="jet_phi__L__Standard__2tag") return 290;
  if (name=="jet_phi__L__Standard__GJetPredicted0To1Tag") return 291;
  if (name=="jet_phi__L__Standard__GJetPredicted1To2Tag") return 292;
  if (name=="jet_nTrack__B__Emerging__0tag") return 293;
  if (name=="jet_nTrack__B__Emerging__1tag") return 294;
  if (name=="jet_nTrack__B__Emerging__2tag") return 295;
  if (name=="jet_nTrack__B__Emerging__GJetPredicted0To1Tag") return 296;
  if (name=="jet_nTrack__B__Emerging__GJetPredicted1To2Tag") return 297;
  if (name=="jet_nTrack__B__Standard__0tag") return 298;
  if (name=="jet_nTrack__B__Standard__1tag") return 299;
  if (name=="jet_nTrack__B__Standard__2tag") return 300;
  if (name=="jet_nTrack__B__Standard__GJetPredicted0To1Tag") return 301;
  if (name=="jet_nTrack__B__Standard__GJetPredicted1To2Tag") return 302;
  if (name=="jet_nTrack__L__Emerging__0tag") return 303;
  if (name=="jet_nTrack__L__Emerging__1tag") return 304;
  if (name=="jet_nTrack__L__Emerging__2tag") return 305;
  if (name=="jet_nTrack__L__Emerging__GJetPredicted0To1Tag") return 306;
  if (name=="jet_nTrack__L__Emerging__GJetPredicted1To2Tag") return 307;
  if (name=="jet_nTrack__L__Standard__0tag") return 308;
  if (name=="jet_nTrack__L__Standard__1tag") return 309;
  if (name=="jet_nTrack__L__Standard__2tag") return 310;
  if (name=="jet_nTrack__L__Standard__GJetPredicted0To1Tag") return 311;
  if (name=="jet_nTrack__L__Standard__GJetPredicted1To2Tag") return 312;
  if (name=="jet_nTrackPostCut__B__Emerging__0tag") return 313;
  if (name=="jet_nTrackPostCut__B__Emerging__1tag") return 314;
  if (name=="jet_nTrackPostCut__B__Emerging__2tag") return 315;
  if (name=="jet_nTrackPostCut__B__Emerging__GJetPredicted0To1Tag") return 316;
  if (name=="jet_nTrackPostCut__B__Emerging__GJetPredicted1To2Tag") return 317;
  if (name=="jet_nTrackPostCut__B__Standard__0tag") return 318;
  if (name=="jet_nTrackPostCut__B__Standard__1tag") return 319;
  if (name=="jet_nTrackPostCut__B__Standard__2tag") return 320;
  if (name=="jet_nTrackPostCut__B__Standard__GJetPredicted0To1Tag") return 321;
  if (name=="jet_nTrackPostCut__B__Standard__GJetPredicted1To2Tag") return 322;
  if (name=="jet_nTrackPostCut__L__Emerging__0tag") return 323;
  if (name=="jet_nTrackPostCut__L__Emerging__1tag") return 324;
  if (name=="jet_nTrackPostCut__L__Emerging__2tag") return 325;
  if (name=="jet_nTrackPostCut__L__Emerging__GJetPredicted0To1Tag") return 326;
  if (name=="jet_nTrackPostCut__L__Emerging__GJetPredicted1To2Tag") return 327;
  if (name=="jet_nTrackPostCut__L__Standard__0tag") return 328;
  if (name=="jet_nTrackPostCut__L__Standard__1tag") return 329;
  if (name=="jet_nTrackPostCut__L__Standard__2tag") return 330;
  if (name=="jet_nTrackPostCut__L__Standard__GJetPredicted0To1Tag") return 331;
  if (name=="jet_nTrackPostCut__L__Standard__GJetPredicted1To2Tag") return 332;
  if (name=="jet_csv__B__Emerging__0tag") return 333;
  if (name=="jet_csv__B__Emerging__1tag") return 334;
  if (name=="jet_csv__B__Emerging__2tag") return 335;
  if (name=="jet_csv__B__Emerging__GJetPredicted0To1Tag") return 336;
  if (name=="jet_csv__B__Emerging__GJetPredicted1To2Tag") return 337;
  if (name=="jet_csv__B__Standard__0tag") return 338;
  if (name=="jet_csv__B__Standard__1tag") return 339;
  if (name=="jet_csv__B__Standard__2tag") return 340;
  if (name=="jet_csv__B__Standard__GJetPredicted0To1Tag") return 341;
  if (name=="jet_csv__B__Standard__GJetPredicted1To2Tag") return 342;
  if (name=="jet_csv__L__Emerging__0tag") return 343;
  if (name=="jet_csv__L__Emerging__1tag") return 344;
  if (name=="jet_csv__L__Emerging__2tag") return 345;
  if (name=="jet_csv__L__Emerging__GJetPredicted0To1Tag") return 346;
  if (name=="jet_csv__L__Emerging__GJetPredicted1To2Tag") return 347;
  if (name=="jet_csv__L__Standard__0tag") return 348;
  if (name=="jet_csv__L__Standard__1tag") return 349;
  if (name=="jet_csv__L__Standard__2tag") return 350;
  if (name=="jet_csv__L__Standard__GJetPredicted0To1Tag") return 351;
  if (name=="jet_csv__L__Standard__GJetPredicted1To2Tag") return 352;
  //[[[end]]]
  
  return -1;
}

TH1F*
EmJetHistos::Get1D(string name)
{
  unsigned index = GetHistoIndex(name);
  assert(vector_hist1d.size()>index); // Make sure index exists first
  auto histPointer = vector_hist1d[index];
  assert(histPointer);
  return NULL;
}

void
EmJetHistos::fillToVector()
{
  vector_hist1d.reserve(hist1d.size());
  for (const auto & kv : hist1d) {
    string name = kv.first;
    auto histPointer = kv.second;
    assert( histPointer ); // Make sure pointer is not null
    assert( vector_hist1d.size() == unsigned(GetHistoIndex(name)) ); // Make sure histogram index is correct
    vector_hist1d.push_back(histPointer);
  }
}
